### ISSUE TITLE
Yiynova MSP19U+ Chrome Windows 7 -- Extension Not Supporting Tablet

### ISSUE THREAD

**Issue by queengooborg** [Agamnentzar/chrome-stylus-pressure#1]
After finishing helping Dr. Dooggle with his new tablet, we tried to draw on aggie.io to see if the pressure sensitivity worked within there.  However, we found out that pressure sensitivity doesn't work.  We looked on your help page, and noted the Chrome extension supports pressure "for all WinTab compatible tablets."  We're certain that the Yiynova tablets use WinTab (the help text on the control panel reads "Wintab32"), but perhaps there is some extra setup to do?

**Comment by Agamnentzar** [comment]
Did you install the extension: [chrome web store](https://chrome.google.com/webstore/detail/stylus-pressure/ecelnbeiglepohnlccefodfpmedepoll) and additional native part: [StylusPressurePlugin.msi](https://github.com/Agamnentzar/chrome-stylus-pressure/releases/download/1.0.1/StylusPressurePlugin.msi) ? If the native part is missing or not working the brush icon in your browser should be red and provide a link to native plugin when you click it. If everything works correctly it should turn grey. If pressure is not working at any time you should also click on the brush icon and use "restart" and see if it helps.

**Comment by queengooborg** [comment]
Already installed from the Chrome web store and the Windows application.  Also tried restarting the extension.  Didn’t help.

**Comment by Agamnentzar** [comment]
Do you get any message in Chrome dev console ?

**Comment by queengooborg** [comment]
Whoops, I just noticed that I never closed this, sorry!  Turns out it was a problem with the Yiynova drivers... >~<
