### ISSUE TITLE
Extension believes it's working, but there's no pressure sensitivity.

### ISSUE THREAD

**Issue by IDLauncher** [Agamnentzar/chrome-stylus-pressure#2]
[Proof that the plugin thinks it's working even though it does not:](http://i.imgur.com/Dl8bBjX.png)

Relevant Info:
OS: Windows 10 - 64 bit.
[Tablet - 10x6.25 Inches Graphic Drawing Tablet w/ 8 Hot Key (160-ha60-990)](https://www.monoprice.com/product?c_id=108&cp_id=10841&cs_id=1084102&p_id=6814)

Chrome Dev Tools Console tab says nothing.

Drivers tried:
http://downloads.monoprice.com/files/drivers/6814_Drivers_Win_2X7_111114.zip (Older)
http://www.uc-logic.com/upload/flash//driver/Legacy/Driver%208%20D20140305D20140214_4.zip (Newer)

**Comment by Agamnentzar** [comment]
Is the table working fine with other software like SAI or Photoshop ?

If the WinTab service is not working properly, maybe this will help: [troubleshooting-Monoprice.pdf](http://aztcs.org/meeting_notes/winhardsig/tablets/Monoprice/troubleshooting-Monoprice.pdf)

Plugin will say it works fine if it managed to connect to the service, it should show errors in console if initialization failed for any reason though.

btw: on windows 10 you should be able to use Edge without need for any plugins.

I made alternative version of the plugin for Windows 8+ that should work with any tablet, but it's less tested and I'd need to compile it.

**Comment by IDLauncher** [comment]
Works fine in Photoshop, and FireAlpaca.

Does not give pressure sensitivity in Edge.

WinTab service is in fact on and running.
