### ISSUE TITLE
Windows 10 StylusPressurePlugin.exe error at Utils.cpp line 77

### ISSUE THREAD

**Issue by abucraft** [Agamnentzar/chrome-stylus-pressure#3]
Windows version: 10.0.14393.206
![image](https://cloud.githubusercontent.com/assets/8390906/19835692/26a0d3ec-9ec9-11e6-8783-e99f3ee07495.png)  
It works fine after I delete this line and rebuild it by visual studio 2015 community version.  
My tablet is UGEE cv720 which uses wintab. I think it could be better if listening these two types of signal in one native program.

**Comment by Agamnentzar** [comment]
Fixed and updated the extension f218537e3d4109944d766c7d74d9592d108733c9
