### ISSUE TITLE
There is no any pressure sensitivity on Internet Explorer 11

### ISSUE THREAD

**Issue by skinyxxx** [Agamnentzar/chrome-stylus-pressure#4]
Info: Windows 7 - 64bit
Browser: Internet Explorer 11 , Chrome
(already install the StylusPressurePlugin1.0.3)

Situation:
1.On the homepage of aggie,it says[ Edge and  Internet Explorer 11 stylus pressure is supported natively by the browser]   but there is no any pressure when i try using  Internet Explorer 11

2.The pressure it is perfectly runs well on chorme by following the way to install the extension

**Comment by Agamnentzar** [comment]
It's actually only on Windows 8 and 10, Windows 7 doesn't natively support stylus pressure. I should add that to the description probably.

**Comment by skinyxxx** [comment]
But why not make it work on windows 7? Especially, there are so many users of win7. cuz it is more stable than win8 or win10.

And here is the other issues:

1. is the pencil has no pressure sensitivity which i dont see it?

2.the shortcut of eyedropper should make its function like photoshop   it will be more easy to use
(the eyedropper will be selected as long as u hold the key   it will back to pen when u loosen the key)

3.it is really good to see lasso selection on aggie, and i think it is better add a fill tool for collocating

4.is it only one public room on the home page of aggie? how can we make a room in aggie?

**Comment by skinyxxx** [comment]
But why not make it work on windows 7? Especially, there are so many users of win7. cuz it is more stable than win8 or win10.

And here is the other issues:

1.is the pencil has no pressure sensitivity which i dont see it?

2.the shortcut of eyedropper should make its function like photoshop it will be more easy to use
(the eyedropper will be selected as long as u hold the key it will back to pen when u loosen the key)

3.it is really good to see lasso selection on aggie, and i think it is better add a fill tool for collocating

4.is it only one public room on the home page of aggie? how can we make a room in aggie?

**Comment by Agamnentzar** [comment]
> But why not make it work on windows 7

Ask Microsoft why they didn't implement it there.

1. Check if you have pressure sensitivity checked in brush settings, it's that second small box next to `size` label.

2. It already works this way, just hold <kbd>I</kbd> also works if you hold <kbd>alt</kbd> just like in photoshop.

3. You mean paint bucket tool, I plan to add it eventually

4. You just press that huge button saying `New Drawing` or if you're already in a drawing use `Drawing > New` menu option

Also, this is not place for reporting issues for `aggie.io`

**Comment by skinyxxx** [comment]
here is two screenshots:
first one is by using pencil  http://chuantu.biz/t5/131/1499701293x2890174028.png
second one is by using brush  http://chuantu.biz/t5/131/1499701215x242984951.png
looks like it has pressure when use brush, but no pressure with pencil
am i all get wrong?

im sorry for reporting these issues here 
can you suggest a way or a place to me for sending feedback of aggie?
and thank you for making effort to this nice creation

**Comment by Agamnentzar** [comment]
Oh right, this tool doesn't support pressure, it's meant for precision pixel drawing so I assumed the pressure wouldn't make sense for it.

I don't take feedback for aggie.io because I don't really have time to work on it

**Comment by skinyxxx** [comment]
ok got it  ( just wish it would work with pencil )

"dont take feedback for aggie"
is that mean there is no update of aggie any more?
anyway, thank you so much for talking to me
