### ISSUE TITLE
downloading issues

### ISSUE THREAD

**Issue by drexillariver** [Agamnentzar/chrome-stylus-pressure#5]
hello, i am not sure weather you still check here.
If you do i could use some help, see ive been trying to use your "aggie.io" for a bit but i have been unable to get the pen pressure to work. yes i have the extension, yes i downloaded the files.
i use google chrome,
i also tried re-installing the files but even then, when i tried to re-download them it said i already had the latest software installed? is there an uninstaller i have to use?

**Comment by Agamnentzar** [comment]
What tablet and system do you use ?
