### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by norashinshi** [Agamnentzar/chrome-stylus-pressure#6]
After trying to install the msi file, my anti-virus went off and quarantined some files. Now I can neither install, repair or uninstall the msi file.

And when I try installing I get the following error message;
"Error writing to file: C:\Program Files (x86)\StylusPressurePlugin\StylusPressurePlugin.exe
Verify the you have access to that directory."

But when I go to the directory nothing is there.

Thanks in advanced

**Comment by Agamnentzar** [comment]
It seems that the antivirus somehow broke the installation, I don't have any experience in dealing with antiviruses. You can try disabling the antivirus and trying to re-install it, otherwise I'm afraid you'll have to consult your antivirus support or forums for help.
